### ISSUE TITLE
NSIS install script mentions local username

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#10]
`"C:\Users\sveni\Documents\PCKram\SpigotInstallation\Build\Spigot.bmp"`

**Comment by josephworks** [comment]
Lines 16, 24, 38

**Comment by KastenKlicker** [comment]
I was to lazy to change this, but maybe I will change it. Maybe

**Comment by KastenKlicker** [comment]
Now it's gone.
