### ISSUE TITLE
Only provide latest minor releases

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#11]
For example:

InstallSpigot1.9.2.py - No | 
-- |
 **InstallSpigot1.9.4.py - Yes**
 InstallSpigot1.9.py - No

**Comment by KastenKlicker** [comment]
I'm asking polite: "What?" Please explain more.

**Comment by josephworks** [comment]
No one is going to download 1.9.2 for example, it would make the repository more lightweight if you didn't provide it. Most people upgrade to the latest minor release as soon as it is released.
