### ISSUE TITLE
Use Aikar's flags

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#12]
https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/ :
```
java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch  -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=true -Daikars.new.flags=true -jar paperclip.jar nogui
```

Note: Aikar's flags do not use all 10Gb of ram unless you are using oraclejava. You probably shouldn't use OracleJava on a Minecraft server anyways.

**Comment by KastenKlicker** [comment]
Never heard of this, but shouldn`t UseConcMarkSweepGC make this job?

**Comment by josephworks** [comment]
It would do part of the job, but it would be better to use the whole command. Aikar learned the JVM and created an excellent command to run Minecraft servers.
