### ISSUE TITLE
Scripts Ping localhost to burn 5 seconds.

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#15]
Replace `echo Finished! && @ping -n 5 localhost> nul && exit` --> `timeout 5`
That way people know that their computer hasn't frosen and is still processing something.

**Comment by KastenKlicker** [comment]
With my last commit it's only wait for 2 seconds now. I think that's okay.

**Comment by josephworks** [comment]
Ok, sounds good
