### ISSUE TITLE
Option for Custom Jar

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#2]
Add the option to use a custom Jar file.

**Comment by KastenKlicker** [comment]
I made one program with python tkinter, but my I'm new to Tkinter so it will become more improvments over the time. Can you give me feedback if it is working correctly? (Choosing file and creating start batch)

**Comment by josephworks** [comment]
Ok sure!

**Comment by josephworks** [comment]
![image](https://user-images.githubusercontent.com/18745823/81607851-314b2680-938a-11ea-97d3-dc0e27040034.png)
The Select file does not open a file dialog.

**Comment by KastenKlicker** [comment]
You have to choose a name for your server. I think I need to edit the Label next to the inputbox, so not only I understand what it means. xD

**Comment by josephworks** [comment]
ok, great to know!

**Comment by KastenKlicker** [comment]
Did it work at least?

**Comment by josephworks** [comment]
I have to retry it.
I will RN.

**Comment by josephworks** [comment]
Ok, it worked.
