### ISSUE TITLE
Download Spigot from buildserver

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#4]
It appears that the Jar is being built with buildtools, this is going to use a lot of computer resources and is not ideal for server admins.

**Comment by KastenKlicker** [comment]
The installer uses BuildTools on few newer versions to support the newest Build automatically. I wanted to use the files from CraftBukkit, but many are not on the newest version. 

Edit:
All Buildfiles from Buildtools are destroyed after installation process.

**Comment by josephworks** [comment]
Ok, I didn't notice this until after I created the issue.
