### ISSUE TITLE
Make binaries external

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#5]
I see the Install and firstrun exes are in the repo (https://github.com/KastenKlicker/SpigotInstaller/tree/master/Build). It would be better to make these external.

**Comment by KastenKlicker** [comment]
I recommend to start the server with a shell or batch for mutliple system, better security and custom start parameters, so don't upload to an other source.

**Comment by josephworks** [comment]
I meant, upload these to a non-git service, so they aren't making the repo large. #11 could also be an alternative.

**Comment by KastenKlicker** [comment]
Do you know a good website for uploading the files? I don't want to remove any versions.

**Comment by josephworks** [comment]
not sure, but it shouldn't be a file hoster that doesn't allow instant downloads.

This would be more of an enhancement for the future.

**Comment by KastenKlicker** [comment]
I made them external. I will remove the files from the repo after I released the update. Would be cool if you can download the lastest and test a version!

**Comment by josephworks** [comment]
Ok, I will rn.

**Comment by KastenKlicker** [comment]
I removed them, know the repo is thin.
