### ISSUE TITLE
Dialog text is unclear

### ISSUE THREAD

**Issue by josephworks** [KastenKlicker/SpigotInstaller#7]
For example "The Server starts now for the first time" --> "The Server will now start for the first time" or "The server will now start!"

**Comment by KastenKlicker** [comment]
My English is not the best, but I learned the last two weeks for my final english exams, so many thing may become better soon.

**Comment by josephworks** [comment]
Ok, sounds good!

**Comment by KastenKlicker** [comment]
I changed it.
